#ifndef _LLF_MP_H
#define _LLF_MP_H

#define LLF_MP_TAG			0xFF


#ifdef RL6531_VB
#define CONFIG_BANK_A1_ENTRY_POINT_OFFSET    SBLK_OFFSET_BANK_A1_ENTRY_POINT
#define CONFIG_BANK_A2_ENTRY_POINT_OFFSET    SBLK_OFFSET_BANK_A2_ENTRY_POINT
#endif
#if defined(RL6577_VA)
#define CONFIG_FE_OPTION1		SBLK_OFFSET_FE_OPTION1
#define CONFIG_BE_OPTION1		SBLK_OFFSET_BE_OPTION1
#define CONFIG_LLF_NOBAD_SBLK		SBLK_OFFSET_LLF_NOBAD_SBLK
#define CONFIG_DISABLE_RAED_PARA		SBLK_OFFSET_DISABLE_RAED_PARA
#define CONFIG_REDUCE_DATA_BUFF_CNT  SBLK_OFFSET_REDUCE_DATA_BUFF_CNT
#endif

#define CONFIG_SDRC_PAGE_NUM    SBLK_OFFSET_SDRC_PAGE_NUM
#define CONFIG_LLF_MODE         SBLK_OFFSET_LLF_MODE
#define CONFIG_NANDID_OFFSET    SBLK_OFFSET_FLASH_VENDOR_NUM
#define CONFIG_CHNUM_OFFSET     SBLK_OFFSET_CH_NUM
#define CONFIG_CENUM_OFFSET     SBLK_OFFSET_CE_NUM
#define CONFIG_BANKNUM_OFFSET   SBLK_OFFSET_BANK_NUM
#define CONFIG_INTERFACE_OFFSET SBLK_OFFSET_FR_IF_TYPE
#define CONFIG_CLOCK_OFFSET     SBLK_OFFSET_FR_CLK_MODE
#define CONFIG_CLK_DOWN_OFFSET  SBLK_OFFSET_FR_CLK_OFFSET
#define CONFIG_TOTAL_BLK_OFFSET SBLK_OFFSET_BLOCK_NUM_PER_LUN
#define CONFIG_BLOCK_NUM_SHIFT_PER_LUN SBLK_OFFSET_BLOCK_NUM_SHIFT_PER_LUN
#define CONFIG_PAGE_NUM_OFFSET  SBLK_OFFSET_PAGE_NUM_PER_BLOCK
#define CONFIG_LUN_NUM_OFFSET   SBLK_OFFSET_LUN_NUM_PER_CE
#define CONFIG_PLANE_NUM_OFFSET SBLK_OFFSET_PLANE_NUM_PER_LUN
#define CONFIG_PAGE_SECTOR_SIZE SBLK_OFFSET_SECTOR_NUM_PER_PAGE
#if defined(RTS5771_FPGA) || defined(RTS5771_VA)
#define CONFIG_PLANE_GROUP_NUM_PER_LUN SBLK_OFFSET_PLANE_GROUP_NUM_PER_LUN
#endif
#define CONFIG_HEADER_SIZE_OFFSET   SBLK_OFFSET_HDR_4B_LEN_FOR_PAGE
#define CONFIG_LBN_BUF_SIZE_OFFSET  SBLK_OFFSET_CACHE_SECTOR_NUM_PER_LBN
#define CONFIG_CAPACITY_OFFSET      SBLK_OFFSET_MAX_LBA
#define CONFIG_MP_TEST_TIME         SBLK_OFFSET_MP_TEST_TIME
#define CONFIG_MP_MODE_SELECT       SBLK_OFFSET_MP_MODE_SELECT
#define CONFIG_DEBUG_LEVEL_SELECT   SBLK_OFFSET_DEBUG_LEVEL_SELECT
#define CONFIG_DEFAULT_DRIVING_SETTING   SBLK_OFFSET_DEFAULT_DRIVING_SETTING
#define CONFIG_LUN_BLOCK_REMAPPING_BASE  SBLK_OFFSET_LUN_BLOCK_REMAPPING_BASE
#define CONFIG_FREE_RATIO_PER_SYSTEM     SBLK_OFFSET_FREE_RATIO_PER_SYSTEM
#define CONFIG_DEFECT_RATIO_PER_CE       SBLK_OFFSET_DEFECT_RATIO_PER_CE

#define CONFIG_DDR_ROW_BIT     SBLK_OFFSET_DDR_ROW_BIT
#define CONFIG_DDR_COL_BIT     SBLK_OFFSET_DDR_COL_BIT
#define CONFIG_DDR_DQ_WIDTH    SBLK_OFFSET_DDR_DQ_WIDTH

#define CONFIG_FR_PHY_TIME0    SBLK_OFFSET_FR_PHY_TIME0
#define CONFIG_FR_PHY_TIME1    SBLK_OFFSET_FR_PHY_TIME1
#define CONFIG_FR_PHY_TIME2    SBLK_OFFSET_FR_PHY_TIME2
#define CONFIG_FR_PHY_TIME3    SBLK_OFFSET_FR_PHY_TIME3
#define CONFIG_FR_PHY_TIME4    SBLK_OFFSET_FR_PHY_TIME4
#define CONFIG_FR_PHY_TIME5    SBLK_OFFSET_FR_PHY_TIME5
#define CONFIG_FR_PHY_TIME6    SBLK_OFFSET_FR_PHY_TIME6
#define CONFIG_FR_PHY_TIME7    SBLK_OFFSET_FR_PHY_TIME7
#define CONFIG_FLASH_TYPE      SBLK_OFFSET_FLASH_TYPE
#define CONFIG_SYS_BANKMAPPING SBLK_OFFSET_SYS_BANKMAPPING
#define CONFIG_FC_DIE_MAPPING_CE SBLK_OFFSET_FC_DIE_MAPPING_CE


#define CONFIG_LLF_SLC_CACHE_NUM        SBLK_OFFSET_SLC_CACHE_MP_BLOCK_NUM
#define CONFIG_LLF_SLC_BUFF_NUM         SBLK_OFFSET_SLC_BUFF_MP_BLOCK_NUM
#define CONFIG_LLF_SLC_CACHE_GC_LIMIT   SBLK_OFFSET_SLC_CACHE_GC_FREE_LIMIT
#define CONFIG_LLF_GC_LIMIT             SBLK_OFFSET_GC_FREE_LIMIT
#define CONFIG_LLF_IS_INTEL_B0KB        SBLK_OFFSET_IS_INTEL_B0KB
#define CONFIG_LLF_SHARED_PAGE_NUM      SBLK_OFFSET_SHARED_PAGE_NUM
#define CONFIG_LLF_PESUDO_SLC_MODE      SBLK_OFFSET_PESUDO_SLC_MODE
#define CONFIG_FWVER_OFFSET             SBLK_OFFSET_FW_VERSION

//===============================RDT setting STRAT====================================//
#define CONFIG_RDT_TEST_OPTION1                   SBLK_OFFSET_RDT_TEST_OPTION1
#define CONFIG_RDT_TEST_OPTION2                   SBLK_OFFSET_RDT_TEST_OPTION2
#define CONFIG_RDT_TEST_OPTION3                   SBLK_OFFSET_RDT_TEST_OPTION3
#define CONFIG_RDT_MAX_ROUND                      SBLK_OFFSET_RDT_MAX_ROUND
#define CONFIG_RDT_IS_NONSLCMODE_TAG              SBLK_OFFSET_RDT_IS_NONSLCMODE_TAG
#define CONFIG__SLC_ROUND_MODE                    SBLK_OFFSET_RDT_SLC_ROUND_MODE
#define CONFIG_RDT_READ_WRITE_FLOW_MODE	          SBLK_OFFSET_RDT_READ_WRITE_FLOW_MODE
#define CONFIG_RDT_MP_TEST_TIME                   SBLK_OFFSET_RDT_MP_TEST_TIME
//#define CONFIG_RDT_TIME_LIMIT                   SBLK_OFFSET_RDT_TIME_LIMIT //unrealized 2 Byte
#define CONFIG_RDT_DEFECT_THRESHOLD               SBLK_OFFSET_RDT_DEFECT_THRESHOLD
#define CONFIG_RDT_ECC_THRESHOLD                  SBLK_OFFSET_RDT_ECC_THRESHOLD
#define CONFIG_RDT_PFAIL_THRESHOLD                SBLK_OFFSET_RDT_PFAIL_THRESHOLD
#define CONFIG_RDT_EFAIL_THRESHOLD                SBLK_OFFSET_RDT_EFAIL_THRESHOLD
#define CONFIG_RDT_RFAIL_THRESHOLD                SBLK_OFFSET_RDT_RFAIL_THRESHOLD
#define CONFIG_RDT_SLCRFAIL_THRESHOLD             SBLK_OFFSET_RDT_SLCRFAIL_THRESHOLD
#define CONFIG_RDT_DEFECT_RATIO_PER_DIE           SBLK_OFFSET_RDT_DEFECT_RATIO_PER_DIE
#define CONFIG_RDT_TLCECCSAFE_THRESHOLD           SBLK_OFFSET_RDT_TLCECCSAFE_THRESHOLD
#define CONFIG_RDT_OPENREADECC_THRESHOLD          SBLK_OFFSET_RDT_OPENREADECC_THRESHOLD
#define CONFIG_RDT_SLCECC_THRESHOLD               SBLK_OFFSET_RDT_SLCECC_THRESHOLD
#define CONFIG_RDT_MAX_ERASE_TIME                 SBLK_OFFSET_RDT_MAX_ERASE_TIME
#define CONFIG_RDT_WRITE_REQUEST                  SBLK_OFFSET_RDT_WRITE_REQUEST
#define CONFIG_RDT_CACHE_WRITE_REQUEST            SBLK_OFFSET_RDT_CACHE_WRITE_REQUEST
#define CONFIG_RDT_TLC_WRITE_REQUEST              SBLK_OFFSET_RDT_TLC_WRITE_REQUEST
#define CONFIG_RDT_DIFFECC_NUMINBANK              SBLK_OFFSET_RDT_DIFFECC_NUMINBANK
#define CONFIG_RDT_ECCFAILLIMIT_InDIFFROUND       SBLK_OFFSET_RDT_ECCFAILLIMIT_InDIFFROUND
#define CONFIG_RDT_PATTERN_MODE                   SBLK_OFFSET_RDT_PATTERN_MODE
#define CONFIG_RDT_PATTERN_0                      SBLK_OFFSET_RDT_PATTERN_0
#define CONFIG_RDT_PATTERN_1                      SBLK_OFFSET_RDT_PATTERN_1
#define CONFIG_RDT_PATTERN_2                      SBLK_OFFSET_RDT_PATTERN_2
#define CONFIG_RDT_PATTERN_3                      SBLK_OFFSET_RDT_PATTERN_3
#define CONFIG_RDT_LLF_NORMAL_EN                  SBLK_OFFSET_RDT_LLF_NORMAL_EN
#define CONFIG_RDT_LLF_PER_DIE_EN                 SBLK_OFFSET_RDT_LLF_PER_DIE_EN
//#define CONFIG_RDT_REREAD_TIMES                 SBLK_OFFSET_RDT_REREAD_TIMES //unrealized
#define CONFIG_RDT_TLC_RETRY_CNT                  SBLK_OFFSET_RDT_TLC_RETRY_CNT
#define CONFIG_RDT_STRESS_CYCLE                   SBLK_OFFSET_RDT_STRESS_CYCLE
//#define CONFIG_RDT__WRITE_SEQUENCE_CYCLE        SBLK_OFFSET_RDT_WRITE_SEQUENCE_CYCLE //unrealized
#define CONFIG_RDT_RETRYPAGENUMLIMT               SBLK_OFFSET_RDT_RETRYPAGENUMLIMT
#define CONFIG_RDT_TLCSTRESSTESTCYCLE             SBLK_OFFSET_RDT_TLCSTRESSTESTCYCLE
#define CONFIG_RDT_RDTDEFECTBSLIMIT               SBLK_OFFSET_RDTDEFECTBSLIMIT
#define CONFIG_RDT_CPU_CLK_DIV                    SBLK_OFFSET_RDT_CPU_CLK_DIV
#define CONFIG_RDT_CUSTOMER                       SBLK_OFFSET_RDT_CUSTOMER
#define CONFIG_RDT_SPEEDTEST_GROUP_NUM            SBLK_OFFSET_RDT_SPEEDTEST_GROUP_NUM
#define CONFIG_RDT_SPEEDTEST_MB_GAP               SBLK_OFFSET_RDT_SPEEDTEST_MB_GAP
#define CONFIG_NAND_TEST_ITEM                     SBLK_OFFSET_NA_TEST_ITEM
#define CONFIG_RDT_CUTOFF_LOW_TEMPERATURE         SBLK_OFFSET_RDT_CUTOFF_LOW_TEMPERATURE
#define CONFIG_RDT_CUTOFF_TEMPERATURE             SBLK_OFFSET_RDT_CUTOFF_TEMPERATURE
#define CONFIG_RDT_LATER_BAD_THRESHOLD            SBLK_OFFSET_RDT_LATER_BAD_THRESHOLD
#define CONFIG_RDT_STRESSTEST_SLC_PAGE            SBLK_OFFSET_RDT_STRESSTEST_SLC_PAGE
#define CONFIG_RDT_STRESSTEST_TLC_PAGE0           SBLK_OFFSET_RDT_STRESSTEST_TLC_PAGE0
#define CONFIG_RDT_STRESSTEST_TLC_PAGE1           SBLK_OFFSET_RDT_STRESSTEST_TLC_PAGE1
#define CONFIG_RDT_STRESSTEST_TLC_PAGE2           SBLK_OFFSET_RDT_STRESSTEST_TLC_PAGE2
#define CONFIG_WSRDT_TEST_OPTION                  SBLK_OFFSET_WSRDT_TEST_OPTION
#define CONFIG_RDT_MIXTEST_MAX_ROUND              SBLK_OFFSET_RDT_MIXTEST_MAX_ROUND
#define CONFIG_RDT_LED_CUSTOM_MADE                SBLK_OFFSET_RDT_LED_CUSTOM_MADE
#define CONFIG_RDT_OPENREAD_MARKBAD               SBLK_OFFSET_RDT_OPENREAD_MARKBAD
#define CONFIG_RDT_RRT_CTR                        SBLK_OFFSET_RDT_RRT_CTR
#define CONFIG_RDT_SINGLE_TEST_CTR                SBLK_OFFSET_RDT_SINGLE_TEST_CTR
#define CONFIG_RDT_MARK_PF_CTR                    SBLK_OFFSET_RDT_MARK_PF_CTR
#define CONFIG_RDT_MULTI_CORE_OPTION              SBLK_OFFSET_RDT_MULTI_CORE_OPTION
#define CONFIG_RDT_DISABLE_LINK_RAMDISK           SBLK_OFFSET_RDT_DISABLE_LINK_RAMDISK
#define CONFIG_RDT_AFTERFIRSTROUND_MARKBANK       SBLK_OFFSET_RDT_AFTERFIRSTROUND_MARKBANK
#define CONFIG_RDT_BLK_RETRY_RATIO                SBLK_OFFSET_RDT_BLK_RETRY_RATIO
#define CONFIG_RDT_BANK_RETRY_RATIO               SBLK_OFFSET_RDT_BANK_RETRY_RATIO
#define CONFIG_RDT_WriteSequenceCount             SBLK_OFFSET_RDT_WriteSequence_CNT
#define CONFIG_RDT_SnapReadTest                   SBLK_OFFSET_RDT_SnapReadTest
#define CONFIG_RDT_WriteReadMixTest               SBLK_OFFSET_RDT_WriteReadMixTest
#define CONFIG_RDT_SLCSpecialTestRound            SBLK_OFFSET_RDT_SLCSpecialTestRound
#define CONFIG_RDT_RETRY_INDEX_SHIFT              SBLK_OFFSET_RDT_RETRY_INDEX_SHIFT
#define CONFIG_RDT_PF2RFCNT                       SBLK_OFFSET_RDT_PF2RF_CNT
#define CONFIG_RDT_MODE4_DELAY                    SBLK_OFFSET_RDT_MODE4_DELAY
#define CONFIG_RDT_MODE4_BATCHSIZE                SBLK_OFFSET_RDT_MODE4_BATCHSIZE
#define CONFIG_RDT_WRMIX_MARK_BANK                SBLK_OFFSET_RDT_WRMIX_MARK_BANK
#define CONFIG_RDT_ROUND_MODE                     SBLK_OFFSET_RDT_ROUND_MODE

//===============================RDT setting END====================================//

#define CONFIG_AES_KEY0              SBLK_OFFSET_AES_KEY0
#define CONFIG_AES_KEY1              SBLK_OFFSET_AES_KEY1
#define CONFIG_AES_KEY2              SBLK_OFFSET_AES_KEY2
#define CONFIG_AES_KEY3              SBLK_OFFSET_AES_KEY3
#define CONFIG_AES_KEY4              SBLK_OFFSET_AES_KEY4
#define CONFIG_AES_KEY5              SBLK_OFFSET_AES_KEY5
#define CONFIG_AES_KEY6              SBLK_OFFSET_AES_KEY6
#define CONFIG_AES_KEY7              SBLK_OFFSET_AES_KEY7
#define CONFIG_AES_MODE_SEL          SBLK_OFFSET_AES_MODE_SEL
#define CONFIG_FC_DIFF_EN            SBLK_OFFSET_FC_DIFF_EN
#define CONFIG_NAND_ODT_EN           SBLK_OFFSET_NAND_ODT_EN
#define CONFIG_NAND_ODT_CFG          SBLK_OFFSET_NAND_ODT_CFG
#define CONFIG_AUTO_CALIBRATE_EN     SBLK_OFFSET_AUTO_CALIBRATE_EN
#define CONFIG_ZQ_K_EN			     SBLK_OFFSET_ZQ_K_EN

#define CONFIG_FC_DRIVESTRENGTH      SBLK_OFFSET_FC_DRIVESTRENGTH
#define CONFIG_FC_DRISTR_PN_CFG0     SBLK_OFFSET_FC_DRISTR_PN_CFG0
#define CONFIG_FR_PAD_DQS_ODT_CTRL   SBLK_OFFSET_FR_PAD_DQS_ODT_CTRL
#define CONFIG_FR_PAD_DQ_RE_ODT_CTRL SBLK_OFFSET_FR_PAD_DQ_RE_ODT_CTRL
#define CONFIG_FR_PAD_DQS_ODT_CFG    SBLK_OFFSET_FR_PAD_DQS_ODT_CFG
#define CONFIG_FR_PAD_DQ_RE_ODT_CFG  SBLK_OFFSET_FR_PAD_DQ_RE_ODT_CFG
#define CONFIG_NAND_DRISTR           SBLK_OFFSET_NAND_DRISTR
#define CONFIG_NAND_TSB_DRISTR       SBLK_OFFSET_NAND_TSB_DRISTR
#define CONFIG_NAND_VREF_EN          SBLK_OFFSET_NAND_VREF_EN
#define CONFIG_FC_DRISTR_PN_CFG0     SBLK_OFFSET_FC_DRISTR_PN_CFG0
#define CONFIG_FC_DRISTR_PN_CFG1     SBLK_OFFSET_FC_DRISTR_PN_CFG1
#define CONFIG_FC_DRISTR_PN_CFG2     SBLK_OFFSET_FC_DRISTR_PN_CFG2
#define CONFIG_FC_DRISTR_PN_CFG3     SBLK_OFFSET_FC_DRISTR_PN_CFG3

#define CONFIG_SPECI_RDT_TAG         SBLK_OFFSET_SPECI_RDT_TAG
#define CONFIG_FULL_PAGE_PER_BLOCK   SBLK_OFFSET_FULL_PAGE_PER_BLOCK
#define CONFIG_STABLE_ENTRYSIZE_SHIFT   SBLK_OFFSET_STABLE_ENTRYSIZE_SHIFT
#define CONFIG_CHECK_CACHE_ERRBIT_LIMIT SBLK_OFFSET_CHECK_CACHE_ERRBIT_LIMIT
#define CONFIG_TEMPERATURE_OFFSET    SBLK_OFFSET_TEMPERATURE_OFFSET
#define CONFIG_TEMPERATURE_MIN       SBLK_OFFSET_TEMPERATURE_MIN
#define CONFIG_TEMPERATURE_MAX       SBLK_OFFSET_TEMPERATURE_MAX
#define CONFIG_TEMPERATURE_FIX       SBLK_OFFSET_FIX_TEMPERATURE
#define CONFIG_SMART_INFO            SBLK_OFFSET_SMART_INFO
#define CONFIG_SMART_INFO1           SBLK_OFFSET_SMART_INFO1
#define CONFIG_EXT_TT1               SBLK_OFFSET_EXT_TT1
#define CONFIG_TEMPERATURE_LIMIT     SBLK_OFFSET_TEMPERATURE_LIMIT
#define CONFIG_EXT_TT2               SBLK_OFFSET_EXT_TT2
#ifdef MST_MERGE
#define CONFIG_MST_MERGE			 SBLK_OFFSET_MST_MERGE
#endif
#define CONFIG_MARK_TOTAL_BAD	     SBLK_OFFSET_MARK_TOTAL_BAD
#define CONFIG_LATER_BAD_THRESHOLD	 SBLK_OFFSET_LATER_BAD_THRESHOLD
#define CONFIG_TM1                   SBLK_OFFSET_TM1
#define CONFIG_TM1_LOWER             SBLK_OFFSET_TM1_LOWER
#define CONFIG_TM2                   SBLK_OFFSET_TM2
#define CONFIG_TM2_LOWER             SBLK_OFFSET_TM2_LOWER
#define CONFIG_TCG_SSC_SUPPORT       SBLK_OFFSET_TCG_SSC_SUPPORT

#define CONFIG_NORMAL_CAPACITY_OP    SBLK_OFFSET_NORMAL_CAPACITY_OP
#define CONFIG_LED_LIGHT             SBLK_OFFSET_LED_LIGHT
#define CONFIG_REMAP_TABLE_PER_BANK  SBLK_OFFSET_REMAP_TABLE_PER_BANK

#define CONFIG_RESET_TO_ORIG_DBT     SBLK_OFFSET_RESET_TO_ORIG_DBT

#define CONFIG_DIRECT_TLC_AMOUNT     SBLK_OFFSET_DIRECT_TLC_AMOUNT


#define CONFIG_FCCLKTHROT_EN                SBLK_OFFSET_FCCLKTHROT_EN   //Temperature Throtting
#define CONFIG_LOWTEMPTHROT_UPPER           SBLK_OFFSET_LOWTEMPTHROT_UPPER
#define CONFIG_LOWTEMPTHROT_LOWER           SBLK_OFFSET_LOWTEMPTHROT_LOWER
#define CONFIG_HIGHTEMPTHROT_UPPER          SBLK_OFFSET_HIGHTEMPTHROT_UPPER
#define CONFIG_HIGHTEMPTHROT_LOWER          SBLK_OFFSET_HIGHTEMPTHROT_LOWER
#define CONFIG_TEMPTHROT_UPPER              SBLK_OFFSET_TEMPTHROT_UPPER
#define CONFIG_TEMPTHROT_LOWER              SBLK_OFFSET_TEMPTHROT_LOWER
#define CONFIG_TEMPTHROT_FC_CLOCK           SBLK_OFFSET_TEMPTHROT_FC_CLOCK
#define CONFIG_LOWTEMPTHROT_POWERON_LIMIT   SBLK_OFFSET_LOWTEMPTHROT_POWERON_LIMIT
#define CONFIG_AUTO_CAPACITY_0       SBLK_OFFSET_AUTO_CAPACITY_0
#define CONFIG_AUTO_CAPACITY_1       SBLK_OFFSET_AUTO_CAPACITY_1
#define CONFIG_AUTO_CAPACITY_2       SBLK_OFFSET_AUTO_CAPACITY_2
#define CONFIG_AUTO_CAPACITY_3       SBLK_OFFSET_AUTO_CAPACITY_3
#define CONFIG_AUTO_CAPACITY_4       SBLK_OFFSET_AUTO_CAPACITY_4
#define CONFIG_AUTO_CAPACITY_5       SBLK_OFFSET_AUTO_CAPACITY_5
#define CONFIG_AUTO_CAPACITY_6       SBLK_OFFSET_AUTO_CAPACITY_6
#define CONFIG_AUTO_CAPACITY_7       SBLK_OFFSET_AUTO_CAPACITY_7

#define CONFIG_PAGE_NUM_PER_RAID	SBLK_OFFSET_PAGE_NUM_PER_RAID
#if defined(RL6643_VA)
#define CONFIG_PAGE_NUM_PER_RAID_TLC SBLK_OFFSET_PAGE_NUM_PER_RAID_TLC
#endif
#define CONFIG_FW_FEATURE_SETTING   SBLK_OFFSET_FW_FEATURE_SETTING
#define CONFIG_CONTROLLER_TEMPERATURE_TH	SBLK_OFFSET_CONTROLLER_TEMPERATURE_TH

#ifdef RL6643_VA
#define CONFIG_FE_0x212_LOW_BYTE       SBLK_OFFSET_FE_0x212_LOW_BYTE
#define CONFIG_FE_0x21E_HIGH_BYTE      SBLK_OFFSET_FE_0x21E_HIGH_BYTE
#define CONFIG_PERFORMANCE_CTRL        SBLK_OFFSET_PERFORMANCE_CTRL
#endif

#define CONFIG_SNAP_READ_EN			SBLK_OFFSET_SNAP_READ_EN
#define CONFIG_SATA_SSC_ENABLE              SBLK_OFFSET_SATA_SSC_ENABLE
#if defined(RL6643_VA) || defined(RL6577_VA)
#ifdef SBLK_EXPAND
#define CONFIG_SBLK_BAD_DETECT_EN      SBLK_SBLK_BAD_DETECT_EN
#endif
#endif
#endif
